### ISSUE TITLE
commons-logging 의존성 제거

### ISSUE THREAD

**Issue by neuma573** [neuma573/auto-board#45]
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts

이 경고 메시지는 commons-logging 의존성이 클래스패스에 존재하여 발생하는 문제이다. 현재 프로젝트에서 commons-io 라이브러리를 사용하고 있으며, 이 라이브러리가 commons-logging 의존성을 포함하고 있다.

통상적인 해결방법인 

```
configurations.all {
    exclude group: 'commons-logging', module: 'commons-logging'
}

implementation ('commons-io:commons-io:2.15.1') {
    exclude group: 'commons-logging', module: 'commons-logging'
}

```

는 작동하지 않는다

**Comment by DonggeonMoon** [comment]
commons-logging 의존성이 존재해서 생기는 문제라면 제시해주신 exclusion으로 해결이 돼야 맞는 것 같습니다. gradle 새로고침이나 clean 한 후에도 동일한 증상일까요?

**Comment by neuma573** [comment]
안녕하세요, 일단 gradle clean한 뒤에도 결과가 같았습니다만 다시 한번 시도해봐야겠네요. 조언 감사드립니다.
